version: '3'
services:
  web:
    image: orlea/pleroma:latest
    restart: always
    ports:
      - "127.0.0.1:4050:4000"
    volumes:
      - /mnt/efs/config/prod.secret.exs:/etc/pleroma/config.exs
      - /mnt/efs/config/keys.secret.exs:/etc/pleroma/keys.secret.exs
      - /mnt/efs/emoji:/var/lib/pleroma/static/emoji/custom
      - /mnt/efs/instance/static/instance:/var/lib/pleroma/static/instance
