version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: echo $CIRCLE_BUILD_NUM
      - run:
          command: docker build -t ${DOCKER_USER}/pleroma:latest -f /home/circleci/project/pleroma/Dockerfile .
      - run:
          command: docker build -t ${DOCKER_USER}/pleroma:$CIRCLE_BUILD_NUM -f /home/circleci/project/pleroma/Dockerfile .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push ${DOCKER_USER}/pleroma:latest
      - run:
          command: docker push ${DOCKER_USER}/pleroma:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
